// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQ1EGcY3GxNMalDS_3RUQyCzxpDPAT_0g',
    appId: '1:260849137592:web:08817c4b9865564201814d',
    messagingSenderId: '260849137592',
    projectId: 'fruits-market-613e5',
    authDomain: 'fruits-market-613e5.firebaseapp.com',
    storageBucket: 'fruits-market-613e5.firebasestorage.app',
    measurementId: 'G-KKG36FQ5QV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuSF1kwGbltWzrkuVd-x14k31D5kRTF_s',
    appId: '1:260849137592:android:6803a3147005dff701814d',
    messagingSenderId: '260849137592',
    projectId: 'fruits-market-613e5',
    storageBucket: 'fruits-market-613e5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsnLjGCBw5PY0FDi4f-tNMams4iOXFASI',
    appId: '1:260849137592:ios:c7d4845d6c95a05601814d',
    messagingSenderId: '260849137592',
    projectId: 'fruits-market-613e5',
    storageBucket: 'fruits-market-613e5.firebasestorage.app',
    iosBundleId: 'com.example.fruitshubDashboard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsnLjGCBw5PY0FDi4f-tNMams4iOXFASI',
    appId: '1:260849137592:ios:c7d4845d6c95a05601814d',
    messagingSenderId: '260849137592',
    projectId: 'fruits-market-613e5',
    storageBucket: 'fruits-market-613e5.firebasestorage.app',
    iosBundleId: 'com.example.fruitshubDashboard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQ1EGcY3GxNMalDS_3RUQyCzxpDPAT_0g',
    appId: '1:260849137592:web:9b3aaa95fd39aec901814d',
    messagingSenderId: '260849137592',
    projectId: 'fruits-market-613e5',
    authDomain: 'fruits-market-613e5.firebaseapp.com',
    storageBucket: 'fruits-market-613e5.firebasestorage.app',
    measurementId: 'G-NVFFKZYK76',
  );
}
